routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ConnectionController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MaintenanceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// dd(session('connection'));

// $connection = session('connection');
// \Config::set("database.connections.users_schemas", [
//     "host" => $connection->host,
//     "database" => $connection->database,
//     "driver" => $connection->driver,
//     "username" => $connection->username,
//     "password" => Crypt::decryptString($connection->password)
// ]);

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    // Route::get('/dashboard', function () {
    //     return view('dashboard');
    // })->name('dashboard');

    Route::post('/companies/{company}/users', [CompanyController::class, 'addUser'])->name('companies.addUser');
    Route::delete('/companies/{company}/users/{user}', [CompanyController::class, 'removeUser'])->name('companies.removeUser');
    Route::get('/companies/select', [CompanyController::class, 'myCompanies'])->name('companies.myCompanies');
    Route::post('/companies/select', [CompanyController::class, 'selectCompany'])->name('companies.select');
    Route::resource('/companies', CompanyController::class);

    Route::resource('/connections', ConnectionController::class)->except(['index', 'show']);
    Route::post('/connections/generate/{company}', [ConnectionController::class, 'generate'])->name('connections.generate');


    Route::middleware('conn')->group(function () {
        Route::get('/home', [HomeController::class, 'index'])->name('home.index');
        Route::post('/maintenances/cancel', function (){
            session()->forget('current_maintenance');
            return redirect(route('home.index'));
        })->name('maintenances.cancel');
        Route::resource('/maintenances', MaintenanceController::class);
        Route::get('/customers/select', [CustomerController::class, 'list'])->name('customers.list');
        Route::post('/customers/select', [CustomerController::class, 'select'])->name('customers.select');
        
        Route::resource('/customers', CustomerController::class);

    });
    
});


// Route::middleware('conn')->group(function () {
//     Route::resource('/maintenances', MaintenanceController::class);
// });

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/app/base/companies.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Companies') }}
        </h2>
    </x-slot>
    {{ $companies }}
    <a class="btn btn-primary text-white mb-4" href="{{ route('companies.create') }}">
        <i class="fa fa-plus-circle"></i> {{ __("New company") }}
    </a>
    {{-- <div class="card">
        <div class="card-body">
            <a class="btn btn-primary text-white" href="{{ route('companies.create') }}">
                <i class="fa fa-plus-circle"></i> {{ __("New company") }}
            </a>
            @if($companies->count()>0)
            <companies-list
                class="mb-3"
                :data="{{ $companies->map(function ($e) { 
                    $e->show = route('companies.show', $e->id);
                    $e->edit = route('companies.edit', $e->id);
                    $e->destroy = route('companies.destroy', $e->id);
                    return $e;
                }) }}"
            ></companies-list>
            @else
                <p class="text-muted mt-4 display-4">Sin empresas registradas</p>
            @endif
        </div>
    </div> --}}
    <x-data-table
        :paginate="$companies"
        :columns="[
            [
              'name' => __('Legal identification'),
              'key' => 'legal_id'
            ],
            [
              'name' => __('Shortname'),
              'key' => 'shortname'
            ],
            [
              'name' => __('Full name'),
              'key' => 'fullname'
            ],
            [
              'name' => __('Email'),
              'key' => 'notification_email'
            ],
            [
                'name' => 'Acciones',
                'actions' => [
                    [
                        'method' => 'GET',
                        'route' => 'companies.show',
                        'class' => 'btn-sm btn-success text-white',
                        'icon' => 'far fa-eye'
                    ],
                    [
                        'method' => 'GET',
                        'route' => 'companies.edit',
                        'class' => 'btn-sm btn-primary',
                        'icon' => 'far fa-edit'
                    ],
                    [
                        'method' => 'DELETE',
                        'route' => 'companies.destroy',
                        'class' => 'btn-sm btn-danger',
                        'icon' => 'fas fa-trash',
                    ],
                ]
            ],
        ]"
    ></x-data-table>
    {{ $companies }}
</x-app-layout>

resources/views/app/base/company.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Company') }}
        </h2>
    </x-slot>
    <div class="row">
        <div class="col-md-6 col-lg-8 mb-4">
            @if($editable)
                <form method="POST" action="{{ $isNew ? route('companies.store') : route('companies.update', $company->id)}}">
                    @csrf
                    @if(!$isNew)
                        @method("PUT")
                    @endif
            @endif
            <div class="card">
                <div class="card-header bg-secondary text-white">
                    <i class="fa fa-info-circle"></i> {{ __("Company information") }}
                </div>
                
                @if($editable)
                <div class="card-body">
                    <x-input :options="['label' => __('Short name'), 'name' => 'shortname', 'value' => $company->shortname]"/>
                    <x-input :options="['label' => __('Full name'), 'name' => 'fullname', 'value' => $company->fullname]"/>
                    <x-input :options="['label' => __('Legal identification'), 'name' => 'legal_id', 'value' => $company->legal_id]"/>
                    <x-input :options="['label' => __('Notification email'), 'name' => 'notification_email', 'value' => $company->notification_email]"/>
                </div>
                @else
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                            <h5 class="card-title">{{ $company->shortname }}</h5>
                            <p class="mb-1">{{ $company->fullname }}</p>
                    </li>
                    <li class="list-group-item">
                        <b>{{ __('Legal identification') }}:</b> {{ $company->legal_id }}
                    </li>
                    <li class="list-group-item">
                        <b>{{ __('Notification email') }}:</b> {{ $company->notification_email }}
                    </li>
                </ul>
                @endif
                @if($editable)
                    <div class="card-footer">
                        <button class="btn btn-primary float-right">
                            <i class="fa fa-save"></i> {{ __("Save") }}
                        </button>
                    </div>
                @endif
            </div>
            @if($editable)
                </form>
            @endif
        </div>
        <div class="col-md-6 col-lg-4">
            @if(!$isNew)
            <div class="card mb-4">
                <div class="card-header bg-secondary text-white">
                    <i class="fa fa-users"></i> {{ __("Users related with") }} {{ $company->shortname }}
                </div>
                <div class="list-group list-group-flush">
                    @foreach ($company->users as $user)
                    <div class="list-group-item">
                        @if($editable)
                        <form action="{{ route('companies.removeUser', [$company->id, $user->id]) }}" method="POST">
                            @csrf
                            @method("DELETE")
                            <button class="btn btn-outline-secondary btn-sm float-right">
                                <i class="fa fa-trash"></i>
                            </button>
                        </form>
                            
                        @endif
                        <p class="mb-0">{{ $user->name }}</p>
                        <small class="text-muted">{{ $user->email }}</small>
                    </div>
                    @endforeach
                    @if($editable)
                    <div class="list-group-item">
                        <form action="{{ route('companies.addUser', $company->id) }}" method="POST">
                            @csrf
                            <div class="input-group mb-0">
                                <input type="email" class="form-control" placeholder="{{ __("Email") }}" required name="email">
                                <div class="input-group-append">
                                  <button class="btn btn-primary text-white" type="submit"><i class="fa fa-plus-circle"></i> {{ __("Add") }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    @else
                        @if($company->users->count()<1)
                        <div class="list-group-item">
                            <p class="text-muted mb-0"><i class="fa fa-ban"></i> Sin usuarios asignados</p>
                        </div>
                        @endif
                    @endif
                </div>
            </div>
            @endif
            @if(!$isNew)
            <div class="card">
                <div class="card-header bg-secondary text-white">
                    <i class="fa fa-database"></i> {{ __("Data base schema") }}
                </div>
                @if ($company->connection)
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <b>{{ __("Connection name") }}</b>: {{ $company->connection->name }}
                        </li>
                        <li class="list-group-item">
                            <b>{{ __("Driver") }}</b>: {{ $company->connection->driver }}
                        </li>
                        <li class="list-group-item">
                            <b>{{ __("Host") }}</b>: {{ $company->connection->host }}
                        </li>
                        <li class="list-group-item">
                            <b>{{ __("Port") }}</b>: {{ $company->connection->port }}
                        </li>
                        <li class="list-group-item">
                            <b>{{ __("Database") }}</b>: {{ $company->connection->database }}
                        </li>
                        <li class="list-group-item">
                            <b>{{ __("Username") }}</b>: {{ $company->connection->username }}
                        </li>
                    </ul>
                @else
                <div class="card-body">
                    <p class="h3 text-muted">{{ __('Schema not exist') }}</p>
                    @if($editable)
                    <form action="{{ route('connections.generate',  $company->id) }}" method="POST">
                        @csrf
                        <button class="btn btn-primary mb-2">
                            <i class="fas fa-robot"></i> {{ __('Automatically generate new schema') }}
                        </button>
                    </form>
                    
                    <a href="{{ route('connections.create', ['company' => $company->id]) }}" class="text-primary">
                        <i class="far fa-edit"></i> {{ __('Connect to existing schema') }}
                    </a>
                    @endif
                </div>
                @endif
                @if($editable && !$isNew && $company->connection)
                <div class="card-footer">
                    <div class=" float-right">
                        <a class="btn btn-primary" href="{{ route("connections.edit", $company->connection->id) }}">
                            <i class="fa fa-edit"></i> {{ __("Edit") }}
                        </a>
                        <form action="{{ route('connections.destroy', $company->connection->id) }}" method="POST" style="display: inline-block">
                            @csrf
                            @method("DELETE")
                            <button class="btn btn-danger">
                                <i class="fa fa-trash"></i> {{ __("Delete") }}
                            </button> 
                        </form>
                    </div>
                </div>
                @endif
            </div>
            @endif
        </div>
    </div>
</x-app-layout>

resources/views/app/base/connection.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Connection for') }} {{ $company->shortname }}
        </h2>
    </x-slot>
    <div class="row">
        <div class="col-sm-10 col-md-8 col-lg-6 offset-sm-1 offset-md-2 offset-lg-3">
            @php
                $action = isset($connection->id) ? 
                route("connections.update", $connection->id) : 
                route("connections.store");
            @endphp
            <div class="card">
                <div class="card-header">
                    <a href="{{ route('companies.edit', $company->id) }}" class="btn btn-outline-secondary">
                        <i class="fas fa-chevron-circle-left"></i> {{ __("Go back") }}
                    </a>
                </div>
                <div class="card-body">
                    <form action="{{ $action }}" method="POST" id="main">
                        @csrf
                        @if($connection->id)
                            @method("PUT")
                        @endif
                        @if ($connection->company)
                            <input type="hidden" name="company_id" value="{{ $connection->company->id }}">
                        @else
                            <input type="hidden" name="company_id" value="{{ app('request')->input('company') }}">
                        @endif
                        <p class="h3 mb-1">{{ __("Connection data") }}</p>
                        <x-input :options="['label' => __('Connection name'), 'name' => 'name', 'value' => $connection->name]"></x-input>
                        <x-input :options="['label' => __('Driver'), 'name' => 'driver', 'value' => $connection->driver]"></x-input>
                        <x-input :options="['label' => __('Host'), 'name' => 'host', 'value' => $connection->host]"></x-input>
                        <x-input :options="['label' => __('Port'), 'name' => 'port', 'value' => $connection->port]"></x-input>
                        <x-input :options="['label' => __('Database'), 'name' => 'database', 'value' => $connection->database]"></x-input>
                        <x-input :options="['label' => __('Username'), 'name' => 'username', 'value' => $connection->username ]"></x-input>
                        <x-input :options="['label' => __('Password'), 'name' => 'password', 'value' => $connection->password, 'type' => 'password' ]"></x-input>
                        <x-input :options="['label' => __('Confirm Password'), 'name' => 'password_confirm', 'value' => $connection->password, 'type' => 'password' ]"></x-input>
                    
                    </form>    
                    <form action="#" id="test"></form> 
                </div>
                <div class="card-footer">
                    <div class="float-right">
                        <button class="btn btn-outline-primary" type="submit" form="test">
                            <i class="fas fa-check-circle"></i> {{ __("Test connection") }}
                        </button>
                        <button class="btn btn-primary" type="submit" form="main">
                            <i class="fas fa-save"></i> {{ __("Save") }}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>