routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ConnectionController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MaintenanceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// dd(session('connection'));

// $connection = session('connection');
// \Config::set("database.connections.users_schemas", [
//     "host" => $connection->host,
//     "database" => $connection->database,
//     "driver" => $connection->driver,
//     "username" => $connection->username,
//     "password" => Crypt::decryptString($connection->password)
// ]);

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    // Route::get('/dashboard', function () {
    //     return view('dashboard');
    // })->name('dashboard');

    Route::post('/companies/{company}/users', [CompanyController::class, 'addUser'])->name('companies.addUser');
    Route::delete('/companies/{company}/users/{user}', [CompanyController::class, 'removeUser'])->name('companies.removeUser');
    Route::get('/companies/select', [CompanyController::class, 'myCompanies'])->name('companies.myCompanies');
    Route::post('/companies/select', [CompanyController::class, 'selectCompany'])->name('companies.select');
    Route::resource('/companies', CompanyController::class);

    Route::resource('/connections', ConnectionController::class)->except(['index', 'show']);
    Route::post('/connections/generate/{company}', [ConnectionController::class, 'generate'])->name('connections.generate');


    Route::middleware('conn')->group(function () {
        Route::get('/home', [HomeController::class, 'index'])->name('home.index');
        Route::post('/maintenances/cancel', function (){
            session()->forget('current_maintenance');
            return redirect(route('home.index'));
        })->name('maintenances.cancel');
        Route::resource('/maintenances', MaintenanceController::class);
        Route::get('/customers/select', [CustomerController::class, 'list'])->name('customers.list');
        Route::post('/customers/select', [CustomerController::class, 'select'])->name('customers.select');
        
        Route::resource('/customers', CustomerController::class);

    });
    
});


// Route::middleware('conn')->group(function () {
//     Route::resource('/maintenances', MaintenanceController::class);
// });

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function companies()
    {
        return $this->belongsToMany('App\Models\Company');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/app/users/companies.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Company selection') }}
        </h2>
    </x-slot>
    {{-- {{ $companies }} --}}
    <div class="row">
        <div class="col-sm-8 col-md-6 col-lg-4 offset-sm-2 offset-md-3 offset-lg-4">
            <div class="card">
                <div class="card-header">
                    {{ __("Select a company") }}
                </div>
                <div class="list-group list-group-flush">
                    {{-- <a href="#" class="list-group-item list-group-item-action active">
                        Cras justo odio
                    </a> --}}
                    @foreach ($companies as $company)
                    <form action="{{ route('companies.select') }}" method="POST" id="company-{{ $company->id }}">
                        @csrf
                        <input type="hidden" name="company_id" value="{{ $company->id }}">
                    </form>
                    <button type="submit" form="company-{{ $company->id }}" class="list-group-item list-group-item-action">
                        <p class="mb-1 h5">{{ $company->shortname }}</p>
                        <small>{{ $company->fullname }}</small>                        
                    </button>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/app/users/customer_select.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Customers') }}
        </h2>
    </x-slot>
    <div class="row">
        <div class="col-sm-8 col-md-6 col-lg-4 offset-sm-2 offset-md-3 offset-lg-4">
            <div class="card">
                <div class="card-header">
                    {{ __("Select customer") }}
                </div>
                <div class="list-group list-group-flush">
                    @foreach ($customers as $customer)
                    <form action="{{ route('customers.select') }}" method="POST" id="customer-{{ $customer->id }}">
                        @csrf
                        <input type="hidden" name="customer_id" value="{{ $customer->id }}">
                    </form>
                    <button type="submit" form="customer-{{ $customer->id }}" href="#" class="list-group-item list-group-item-action">
                        <p class="mb-1 h5">{{ $customer->shortname }}</p>
                        <small>{{ $customer->fullname }}</small>                        
                    </button>
                    @endforeach
                </div>
                <div class="card-footer">
                    <a href="" class="btn btn-primary float-right">
                        <i class="fas fa-plus-circle"></i> {{ __("Add new customer") }}
                    </a>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/app/users/customers_create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
             
            @isset($customer->shortname)
                {{ __('Customer') }} - {{ $customer->shortname }}
            @else
                 {{ __("New customer") }}
            @endisset
        </h2>
    </x-slot>
    {{-- {{ $customer }} --}}
    @if ($editable)
    @if ($isNew)
    <form action="{{ route('customers.store') }}" method="POST">
    @else
    <form action="{{ route('customers.update', $customer->id) }}" method="POST">
        
        @method('PUT')
    @endif
   
        @csrf
    @endif
        <div class="card">
            <div class="card-header">
                {{ __('Customer') }}
            </div>
            <ul class="list-group list-group-flush">
                
                @if ($editable)
                    <li class="list-group-item">
                        <x-input :options="['label' => __('Short name'), 'name' => 'shortname', 'value' => $customer->shortname]"/>
                    </li>
                    <li class="list-group-item">
                        <x-input :options="['label' => __('Full name'), 'name' => 'fullname', 'value' => $customer->fullname]"/>
                    </li>
                @else
                    <li class="list-group-item">
                        <p class="mb-1 h5 text-primary">{{ $customer->shortname }}</p>
                        <small class="text-muted">{{ $customer->fullname }}</small>
                    </li>
                @endif
                <li class="list-group-item">
                    @if ($editable)
                        <x-input :options="['label' => __('Legal identification'), 'name' => 'legal_id', 'value' => $customer->legal_id]"/>
                    @else
                        <b>{{ __('Legal identification') }}: </b>{{ $customer->legal_id }}
                    @endif
                </li>
                <li class="list-group-item">
                    @if ($editable)
                        <x-input :options="['label' => __('Notification email'), 'name' => 'notification_email', 'value' => $customer->notification_email]"/>
                    @else
                        <b>{{ __('Notification email') }}: </b>{{ $customer->notification_email }}
                    @endif
                </li>
            </ul>
            @if ($editable)
                <div class="card-footer">
                    <button class="btn btn-primary float-right">
                        {{ __("Save") }}
                    </button>
                </div>
            @endif
        </div>
    @if ($editable)
    </form>
    @endif
</x-app-layout>

resources/views/app/users/customers_index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Customers') }}
        </h2>
    </x-slot>
    <a href="{{ route('customers.create') }}" class="btn btn-primary mb-4">
        <i class="fa fa-plus-circle"></i> {{ __("Add customer") }}
    </a>
    <x-data-table
        :paginate="$customers"
        :columns="[
            [
              'name' => 'Empresa',
              'key' => 'shortname'
            ],
            [
              'name' => 'Cédula juridica',
              'key' => 'legal_id'
            ],
            [
              'name' => 'Correo para notificación',
              'key' => 'notification_email'
            ],
            [
                'name' => 'Acciones',
                'actions' => [
                    [
                        'method' => 'GET',
                        'route' => 'customers.show',
                        'class' => 'btn-sm btn-success text-white',
                        'icon' => 'far fa-eye'
                    ],
                    [
                        'method' => 'GET',
                        'route' => 'customers.edit',
                        'class' => 'btn-sm btn-primary',
                        'icon' => 'far fa-edit'
                    ],
                    [
                        'method' => 'DELETE',
                        'route' => 'customers.destroy',
                        'class' => 'btn-sm btn-danger',
                        'icon' => 'fas fa-trash',
                    ],
                ]
            ],
        ]"
    ></x-data-table>
</x-app-layout>

resources/views/app/users/home.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Dashboard') }} - {{ session('company')->shortname }}
        </h2>
    </x-slot>
    {{-- {{ $maintenances }} - {{ $customers }} --}}
    <div class="row mb-3">
        <div class="col-sm-6 col-md-8">
            <div class="d-flex w-100 justify-content-between">
                <h1 class="mb-1">
                    <i class="fas fa-wrench"></i> {{ __("Maintenances") }}
                </h1>
                <a href="{{ route("maintenances.create") }}" class="btn btn-primary mb-3">
                    <i class="fas fa-plus-circle"></i> {{ __("New maintenance") }}
                </a>
              </div>
        </div>
    </div>
    {{ $maintenances }}
    <div class="row">
        <div class="col-sm-6 col-md-8">
            @foreach ($maintenances as $maintenance)
            <div class="card mb-4 shadow">
                <div class="card-header">
                    <div class="d-flex w-100 justify-content-between">
                        <div>
                            
                            <p class="mb-1 h5">
                                <span class="badge bg-primary mb-1">
                                    {{ __('Maintenance') }}  #{{ $maintenance->id }}
                                </span>
                            </p>
                            <p class="mb-1 h5 text-primary">{{ $maintenance->customer->shortname }}</p>
                            <small class="text-muted">{{ $maintenance->customer->fullname }}</small>
                        </div>
                        <div>
                            <span class="badge bg-dark mb-1">
                                <i class="fas fa-calendar-alt"></i> {{ date('d/m/Y', strtotime($maintenance->date)) }}
                            </span>
                            <p class="text-muted small mb-1">
                                <i class="fas fa-clock"></i> {{ date('h:i a', strtotime($maintenance->date)) }}
                            </p>
                        </div>
                    </div>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <b>{{ __("Details lines") }}:</b> 5
                    </li>
                    <li class="list-group-item">
                        <b>{{ __("Technician") }}:</b> {{ $maintenance->tecnical }}
                    </li>
                    <li class="list-group-item">
                        <b>{{ __("Empleado del cliente ") }}:</b> {{ $maintenance->customer_employee }}
                    </li>
                    <li class="list-group-item">
                        <b>{{ __("Report email") }}:</b> {{ $maintenance->report_mail }}
                    </li>
                </ul>
                <div class="card-footer">
                    <a href="{{ route("maintenances.show", $maintenance->id) }}" class="btn btn-primary float-right">
                        <i class="fas fa-info-circle"></i> {{ __("See details") }}
                    </a>
                </div>
            </div>
            @endforeach
            
            @if ($maintenances->total() < 1)
            <div class="card">
                <div class="card-body">
                    <div class="jumbotron">
                        <p class="display-4 mb-1">
                            {{ __("Welcome") }}
                        </p>
                        <p class="lead">
                            {{ __("In this area appears a list of all the maintenance that the company has carried out") }}
                        </p>
                        {{-- <hr class="my-4">
                        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
                        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a> --}}
                    </div>
                </div>
            </div>
            
            @endif
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="card">
                <div class="card-header">
                    <button class="btn btn-secondary btn-sm float-right">
                        {{ __("Manage clients") }}
                    </button>
                    {{ __("My clientes") }}
                </div>
                <div class="list-group list-group-flush">
                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                      <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">List group item heading</h5>
                        <small>3 days ago</small>
                      </div>
                      <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
                      <small>Donec id elit non mi porta.</small>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {{ $maintenances }}
</x-app-layout>

resources/views/app/users/maintenance.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="d-flex w-100 justify-content-between">
            <span>
                <h2 class="h4 font-weight-bold">
                    {{ __('Maintenance') }} {{ $maintenance->id ? '#' . $maintenance->id : 'nuevo' }}
                </h2>
            </span>
            @if ($isNew)
            <form action="{{ route('maintenances.cancel') }}" method="POST">
                @csrf
                <button class="btn btn-danger btn-sm" type="submit">
                    <i class="fas fa-times"></i> {{ __("Cancel current maintenance") }}
                </button>
            </form>
            @endif
        </div>
    </x-slot>
    {{-- {{ $maintenance }} --}}
    
    {{-- {{ $maintenance->details }} --}}

    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header bg-primary text-white">
                    <i class="fas fa-info-circle"></i> {{ __('Maintenance information') }}
                </div>
                <form action="" method="POST" id="save">
                    @csrf
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <b>{{ __("Customer") }}:</b> 
                            <div>
                                <p class="mb-1 h5 text-primary">{{ $maintenance->customer->shortname }}</p>
                                <small class="text-muted">{{ $maintenance->customer->fullname }}</small>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <b>{{ __("Customer legal id") }}:</b> {{ $maintenance->customer->legal_id }}
                        </li>
                        @if (!$isNew)
                        <li class="list-group-item">
                            <b>{{ __("Date") }}:</b> {{ date('d/m/Y', strtotime($maintenance->date)) }}
                        </li>
                        <li class="list-group-item">
                            <b>{{ __("Hour") }}:</b> {{ date('h:i a', strtotime($maintenance->date)) }}
                        </li>
                        @endif
                        <li class="list-group-item">
                            @if ($editable)
                                <x-input :options="['label' => __('Responsible Technician'), 'name' => 'tecnical', 'required' => true]"/>
                            @else
                                <b>{{ __("Responsible Technician") }}:</b> {{ $maintenance->tecnical }}
                            @endif
                        </li>
                        <li class="list-group-item">
                            @if ($editable)
                                <x-input :options="['label' => __('Customer employee'), 'name' => 'customer_employee', 'required' => true]"/>
                            @else
                                <b>{{ __("Customer employee") }}:</b> {{ $maintenance->customer_employee }}
                            @endif
                        </li>
                        <li class="list-group-item">
                            @if ($editable)
                                <x-input :options="['label' => __('Mail for report'), 'name' => 'report_mail', 'value' => ($maintenance->report_mail?:$maintenance->customer->notification_email), 'required' => true]"/>
                            @else
                                <b>{{ __("Mail for report") }}:</b> {{ $maintenance->report_mail }}
                            @endif
                        </li>
                    </ul>
                </form>
                <div class="card-footer">
                    <button class="btn btn-primary float-right" type="submit" form="save">
                        <i class="fas fa-plus-circle"></i> {{ __("Add details lines") }}
                    </button>
                </div>
            </div>
        </div>
        @if (!$isNew)
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <i class="fas fa-receipt"></i> {{ __("Details lines") }}
                </div>
                <ul class="list-group list-group-flush">
                    @foreach ($maintenance->details as $detail)
                    <li class="list-group-item">
                        <i class="far fa-{{ $detail->execute ? 'check-circle' : 'circle' }}"></i> {{ __("Device") }}:  {{ $detail->device->indentifier }} - {{ $detail->device->description }} {{ $detail->device }}        {{ $detail }}
                    </li>
                    @endforeach
                </ul>
            </div>
        </div>
        @endif
    </div>
</x-app-layout>