routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ConnectionController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MaintenanceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// dd(session('connection'));

// $connection = session('connection');
// \Config::set("database.connections.users_schemas", [
//     "host" => $connection->host,
//     "database" => $connection->database,
//     "driver" => $connection->driver,
//     "username" => $connection->username,
//     "password" => Crypt::decryptString($connection->password)
// ]);

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    // Route::get('/dashboard', function () {
    //     return view('dashboard');
    // })->name('dashboard');

    Route::post('/companies/{company}/users', [CompanyController::class, 'addUser'])->name('companies.addUser');
    Route::delete('/companies/{company}/users/{user}', [CompanyController::class, 'removeUser'])->name('companies.removeUser');
    Route::get('/companies/select', [CompanyController::class, 'myCompanies'])->name('companies.myCompanies');
    Route::post('/companies/select', [CompanyController::class, 'selectCompany'])->name('companies.select');
    Route::resource('/companies', CompanyController::class);

    Route::resource('/connections', ConnectionController::class)->except(['index', 'show']);
    Route::post('/connections/generate/{company}', [ConnectionController::class, 'generate'])->name('connections.generate');


    Route::middleware('conn')->group(function () {
        Route::get('/home', [HomeController::class, 'index'])->name('home.index');
        Route::post('/maintenances/cancel', function (){
            session()->forget('current_maintenance');
            return redirect(route('home.index'));
        })->name('maintenances.cancel');
        Route::resource('/maintenances', MaintenanceController::class);
        Route::get('/customers/select', [CustomerController::class, 'list'])->name('customers.list');
        Route::post('/customers/select', [CustomerController::class, 'select'])->name('customers.select');
        
        Route::resource('/customers', CustomerController::class);

    });
    
});


// Route::middleware('conn')->group(function () {
//     Route::resource('/maintenances', MaintenanceController::class);
// });

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        @livewireStyles

        <!-- Scripts -->
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.js" defer></script>
    </head>
    <body class="bg-light">
        <div id="app">

        
            <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom sticky-top">
                <div class="container">
                    <!-- Logo -->
                    <a class="navbar-brand" href="/">
                        <x-jet-application-mark width="36" />
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav mr-auto">
                            {{-- <x-jet-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                                {{ __('Dashboard') }}
                            </x-jet-nav-link> --}}
                            <x-jet-nav-link href="{{ route('companies.index') }}" :active="request()->routeIs('companies.index')">
                                <i class="fas fa-city"></i> {{ __('Companies') }}
                            </x-jet-nav-link>
                            <x-jet-nav-link href="{{ route('home.index') }}" :active="request()->routeIs('home.index')">
                                <i class="fas fa-home"></i> {{ __('Dashboard') }}
                            </x-jet-nav-link>
                            <x-jet-nav-link href="{{ route('customers.index') }}" :active="request()->routeIs('customers.index')">
                                <i class="fas fa-id-card"></i> {{ __('Customers') }}
                            </x-jet-nav-link>
                        </ul>

                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ml-auto">
                            <!-- Authentication Links -->
                            @if (Auth::user()->companies->count() > 1)
                                <x-jet-nav-link href="{{ route('companies.select') }}" :active="request()->routeIs('companies.select')">
                                    <i class="fas fa-exchange-alt"></i> {{ __('Change company') }}
                                </x-jet-nav-link> 
                            @endif
                            @auth
                                <x-jet-dropdown id="navbarDropdown">
                                    <x-slot name="trigger">
                                        @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                                            <img class="rounded-circle" width="32" height="32" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                                        @else
                                            {{ Auth::user()->name }}
                                        @endif
                                    </x-slot>

                                    <x-slot name="content">
                                        <!-- Account Management -->
                                        <h6 class="dropdown-header small text-muted">
                                            {{ __('Manage Account') }}
                                        </h6>

                                        <x-jet-dropdown-link href="{{ route('profile.show') }}">
                                            {{ __('Profile') }}
                                        </x-jet-dropdown-link>

                                        @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                                            <x-jet-dropdown-link href="{{ route('api-tokens.index') }}">
                                                {{ __('API Tokens') }}
                                            </x-jet-dropdown-link>
                                        @endif

                                    <!-- Team Management -->
                                        @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())

                                            <hr class="dropdown-divider">

                                            <h6 class="dropdown-header">
                                                {{ __('Manage Team') }}
                                            </h6>

                                            <!-- Team Settings -->
                                            <x-jet-dropdown-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}">
                                                {{ __('Team Settings') }}
                                            </x-jet-dropdown-link>

                                            @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                                                <x-jet-dropdown-link href="{{ route('teams.create') }}">
                                                    {{ __('Create New Team') }}
                                                </x-jet-dropdown-link>
                                            @endcan

                                            <hr class="dropdown-divider">

                                            <!-- Team Switcher -->
                                            <h6 class="dropdown-header">
                                                {{ __('Switch Teams') }}
                                            </h6>

                                            @foreach (Auth::user()->allTeams() as $team)
                                                <x-jet-switchable-team :team="$team" />
                                            @endforeach
                                        @endif

                                        <hr class="dropdown-divider">

                                        <!-- Authentication -->
                                        <x-jet-dropdown-link href="{{ route('logout') }}"
                                                            onclick="event.preventDefault();
                                                            document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                        </x-jet-dropdown-link>
                                        <form method="POST" id="logout-form" action="{{ route('logout') }}">
                                            @csrf
                                        </form>
                                    </x-slot>
                                </x-jet-dropdown>
                            @endauth
                        </ul>
                    </div>
                </div>
            </nav>

            <header class="d-flex py-3 bg-white shadow-sm border-bottom">
                <div class="container">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main class="container my-5">
                {{ $slot }}
            </main>

        </div>
        @stack('modals')

        <script src="{{ asset('js/app.js') }}"></script>
        @livewireScripts
        @stack('scripts')

    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.js" defer></script>
    </head>
    <body class="bg-light">
        {{ $slot }}
    </body>
</html>